jenkins-python:
  image: registry.aliyuncs.com/jingshanlb/jenkins-demo-python-app
  labels:
      aliyun.scale: '1'
      aliyun.probe.url: 'tcp://container:5000'
      aliyun.probe.initial_delay_seconds: '10'
      aliyun.routing.port_5000: python-demo  